server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.1.184:3306/sql_help?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: you